spring:
  datasource:
    vendor: H2
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    dialect: org.hibernate.dialect.H2Dialect
    driverClassName: org.h2.Driver
    schema: ''
  jpa:
    hibernate:
      ddl-auto: none